### ISSUE TITLE
Remove hardcoded numbers (use new ENDPOINT)

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffoldeth.io#22]
https://buidlguidl-v3.ew.r.appspot.com/api/stats

![image](https://github.com/scaffold-eth/scaffoldeth.io/assets/2486142/020356c2-d813-44ec-809e-1e0af4b829b7)

![image](https://github.com/scaffold-eth/scaffoldeth.io/assets/2486142/cc100a4a-c4f0-4f6c-a56c-84530c6bdaef)

**Comment by technophile-04** [comment]
Was this supposed to be created at buidlguidl.com repo? Or we are planning to add it here too 🙌 ? 

Just created a PR there https://github.com/BuidlGuidl/buidlguidl.com/pull/18

**Comment by carletex** [comment]
My bad!! haha, was doing many things at the same time

Thanks Shiv!
