### ISSUE TITLE
Hooks section

### ISSUE THREAD

**Issue by carletex** [scaffold-eth/scaffoldeth.io#9]
Let's think about what we want to show there.

As a first iteration, I'll vote for the `useScaffoldContractWrite` hook. A good example sending some args + value, with a button that does writeAsync onClick.

Question: Should we add a "view all hooks" link or some text like that links to the hooks sections in the docs? Maybe not a primary button, it can be just an underlined link.

![image](https://github.com/scaffold-eth/scaffoldeth.io/assets/2486142/d80af930-dc6a-4180-bd11-47ae356958a4)

**Comment by technophile-04** [comment]
> I'll vote for the useScaffoldContractWrite hook. A good example sending some args + value, with a button that does writeAsync onClick. 

++ 

> Should we add a "view all hooks" link or some text like that links to the hooks sections in the docs? Maybe not a primary button, it can be just an underlined link.

++, I am ok with button too but if that doesn't go with other sections a "view all hooks" underline link also works 🙌

**Comment by Pabl0cks** [comment]
I agree with you both.

The [project](https://dappkit.dev/) I took as inspiration for this section is also showcasing all Write examples: Mint / Transfer / Swap / Lock.
